package com.phorest.events.model.message;

public enum FailureReasonType {
    DESTINATION_PERMANENTLY_BLOCKED,
    DESTINATION_PERMANENTLY_UNREACHABLE,
    DESTINATION_TEMPORAIRLY_UNREACHABLE,
    INTERNAL_SYSTEM_ERROR,
    MESSAGE_CONTENT_INVALID,
    MESSAGE_SPAM,
    MESSAGE_TOO_LARGE,
    UNDETERMINED_PERMANENT_ERROR,
    UNDETERMINED_TEMPORARY_ERROR
}
